package MainClass;
import math.RiskCalculation;
import amazon_systems.*;
import cisco_devices.*;
import google_hubs_etc.*;
import google_sensors.*;
import netstick_devices.*;
import xiaomi_routers.*;
import xiaomi_sockets_sensors.*;
import java.io.*;

public class BodyCode {
    public static int number;

    public static void main(String[] args) throws IOException {

        InputStream inputStream = System.in;
        Reader inputStreamReader = new InputStreamReader(inputStream);
        BufferedReader reader = new BufferedReader(inputStreamReader);


        RiskCalculation RiskCalculation_Prod = new RiskCalculation();

        System.out.println("Введите количество устройств:");
        number = Integer.parseInt(reader.readLine());

        for (int i = 0; i < number; i++) {
            System.out.println("Введите однозначный идентификатор устройства в формате Вендор_тип устройства");
            String identifier = reader.readLine();
            switch (identifier) {
               case ("Amazon_Echo_Flex"): Amazon_Echo_Flex Amazon_Echo_Flex_1 = new Amazon_Echo_Flex();
                    Amazon_Echo_Flex_1.KeyboardInput();
                    Amazon_Echo_Flex_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Amazon+Flex&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[0] = Amazon_Echo_Flex_1.Amazon_Echo_Flex_vulnerabilities.length;
                    continue;
               case ("Amazon_Echo_fourth_gen"): Amazon_Echo_fourth_gen Amazon_Echo_fourth_gen_1 = new Amazon_Echo_fourth_gen();
                    Amazon_Echo_fourth_gen_1.KeyboardInput();
                    Amazon_Echo_fourth_gen_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Aamazon&cpe_product=cpe%3A%2F%3Aamazon%3Aecho_plus_firmware");
                    RiskCalculation_Prod.number_of_probabilities[1] = Amazon_Echo_fourth_gen_1.Amazon_Echo_fourth_gen_vulnerabilities.length;
                    continue;
               case ("Amazon_Echo_Show_8"): Amazon_Echo_Show_8 Amazon_Echo_Show_8_1 = new Amazon_Echo_Show_8();
                    Amazon_Echo_Show_8_1.KeyboardInput();
                    Amazon_Echo_Show_8_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Aamazon&cpe_product=cpe%3A%2F%3Aamazon%3Aecho_plus_firmware");
                    RiskCalculation_Prod.number_of_probabilities[2] = Amazon_Echo_Show_8_1.Amazon_Echo_Show_8_vulnerabilities.length;
                    continue;
               case ("August_WiFi_Smart_Lock"): August_WiFi_Smart_Lock August_WiFi_Smart_Lock_1 = new August_WiFi_Smart_Lock();
                    August_WiFi_Smart_Lock_1.KeyboardInput();
                    August_WiFi_Smart_Lock_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Aamazon&cpe_product=cpe%3A%2F%3Aamazon%3Aecho_plus_firmware");
                    RiskCalculation_Prod.number_of_probabilities[3] = August_WiFi_Smart_Lock_1.August_WiFi_Smart_Loc_vulnerabilities.length;
                    continue;
               case ("Ecobee_Smart_Thermostat"): Ecobee_Smart_Thermostat Ecobee_Smart_Thermostat_1 = new Ecobee_Smart_Thermostat();
                    Ecobee_Smart_Thermostat_1.KeyboardInput();
                    Ecobee_Smart_Thermostat_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=thermostat&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[4] = Ecobee_Smart_Thermostat_1.Ecobee_Smart_Thermostat_vulnerabilities.length;
                    continue;
               case ("Ring_Peephole_Cam"): Ring_Peephole_Cam Ring_Peephole_Cam_1 = new Ring_Peephole_Cam();
                    Ring_Peephole_Cam_1.KeyboardInput();
                    Ring_Peephole_Cam_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=telephone+camera&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[5] = Ring_Peephole_Cam_1.Ring_Peephole_Cam_vulnerabilities.length;
                    continue;
               case ("Cisco_1100_Series_Industrial_Integrated_Services_Router"): Cisco_1100_Series_Industrial_Integrated_Services_Router Cisco_1100_Series_Industrial_Integrated_Services_Router_1 = new Cisco_1100_Series_Industrial_Integrated_Services_Router();
                    Cisco_1100_Series_Industrial_Integrated_Services_Router_1.KeyboardInput();
                    Cisco_1100_Series_Industrial_Integrated_Services_Router_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Acisco&cpe_product=cpe%3A%2F%3Acisco%3A1100");
                    RiskCalculation_Prod.number_of_probabilities[6] = Cisco_1100_Series_Industrial_Integrated_Services_Router_1.Cisco_1100_Series_Industrial_Integrated_Services_Router_vulnerabilities.length;
                    continue;
               case ("Cisco_Catalyst_IE3x00_Rugged_Switches"): Cisco_Catalyst_IE3x00_Rugged_Switches Cisco_Catalyst_IE3x00_Rugged_Switches_1 = new Cisco_Catalyst_IE3x00_Rugged_Switches();
                    Cisco_Catalyst_IE3x00_Rugged_Switches_1.KeyboardInput();
                    Cisco_Catalyst_IE3x00_Rugged_Switches_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_product=cpe%3A%2F%3A%3A300_series_managed_switch_firmware");
                    RiskCalculation_Prod.number_of_probabilities[7] = Cisco_Catalyst_IE3x00_Rugged_Switches_1.Cisco_Catalyst_IE3x00_Rugged_Switches_vulnerabilities.length;
                    continue;
               case ("Cisco_Catalyst_IE3400_Heavy_Duty_Series"): Cisco_Catalyst_IE3400_Heavy_Duty_Series Cisco_Catalyst_IE3400_Heavy_Duty_Series_1 = new Cisco_Catalyst_IE3400_Heavy_Duty_Series();
                    Cisco_Catalyst_IE3400_Heavy_Duty_Series_1.KeyboardInput();
                    Cisco_Catalyst_IE3400_Heavy_Duty_Series_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Alenovo&cpe_product=cpe%3A%2F%3A%3A340c-15ast");
                    RiskCalculation_Prod.number_of_probabilities[8] = Cisco_Catalyst_IE3400_Heavy_Duty_Series_1.Cisco_Catalyst_IE3400_Heavy_Duty_Series_vulnerabilities.length;
                    continue;
               case ("Cisco_Catalyst_IR1800_Rugged_Series_Router"): Cisco_Catalyst_IR1800_Rugged_Series_Router Cisco_Catalyst_IR1800_Rugged_Series_Router_1 = new Cisco_Catalyst_IR1800_Rugged_Series_Router();
                    Cisco_Catalyst_IR1800_Rugged_Series_Router_1.KeyboardInput();
                    Cisco_Catalyst_IR1800_Rugged_Series_Router_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Acisco&cpe_product=cpe%3A%2F%3A%3A1801_integrated_service_router");
                    RiskCalculation_Prod.number_of_probabilities[9] = Cisco_Catalyst_IR1800_Rugged_Series_Router_1.Cisco_Catalyst_IR1800_Rugged_Series_Router_vulnerabilities.length;
                    continue;
               case ("Cisco_Catalyst_IR8100_Heavy_Duty_Series_Router"): Cisco_Catalyst_IR8100_Heavy_Duty_Series_Router Cisco_Catalyst_IR8100_Heavy_Duty_Series_Router_1 = new Cisco_Catalyst_IR8100_Heavy_Duty_Series_Router();
                    Cisco_Catalyst_IR8100_Heavy_Duty_Series_Router_1.KeyboardInput();
                    Cisco_Catalyst_IR8100_Heavy_Duty_Series_Router_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Acisco&cpe_product=cpe%3A%2F%3A%3A1801_integrated_service_router");
                    RiskCalculation_Prod.number_of_probabilities[10] = Cisco_Catalyst_IR8100_Heavy_Duty_Series_Router_1.Cisco_Catalyst_IR8100_Heavy_Duty_Series_Router_vulnerabilities.length;
                    continue;
               case ("Redmi_AC2100_Router"): Redmi_AC2100_Router Redmi_AC2100_Router_1 = new Redmi_AC2100_Router();
                    Redmi_AC2100_Router_1.KeyboardInput();
                    Redmi_AC2100_Router_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[11] = Redmi_AC2100_Router_1.Redmi_AC2100_Router_vulnerabilities.length;
                    continue;
               case ("Redmi_AX6_Router"): Redmi_AX6_Router Redmi_AX6_Router_1 = new Redmi_AX6_Router();
                    Redmi_AX6_Router_1.KeyboardInput();
                    Redmi_AX6_Router_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[12] = Redmi_AX6_Router_1.Redmi_AX6_Router_vulnerabilities.length;
                    continue;
               case ("Xiaomi_AC2100_Wireless_Wifi_Router"): Xiaomi_AC2100_Wireless_Wifi_Router Xiaomi_AC2100_Wireless_Wifi_Router_1 = new Xiaomi_AC2100_Wireless_Wifi_Router();
                    Xiaomi_AC2100_Wireless_Wifi_Router_1.KeyboardInput();
                    Xiaomi_AC2100_Wireless_Wifi_Router_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[13] = Xiaomi_AC2100_Wireless_Wifi_Router_1.Xiaomi_AC2100_Wireless_Wifi_Router_vulnerabilities.length;
                    continue;
               case ("Xiaomi_AIoT_Router_AC2350"): Xiaomi_AIoT_Router_AC2350 Xiaomi_AIoT_Router_AC2350_1 = new Xiaomi_AIoT_Router_AC2350();
                    Xiaomi_AIoT_Router_AC2350_1.KeyboardInput();
                    Xiaomi_AIoT_Router_AC2350_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[14] = Xiaomi_AIoT_Router_AC2350_1.Xiaomi_AIoT_Router_AC2350_vulnerabilities.length;
                    continue;
               case ("Xiaomi_AIoT_Router_AX9000"): Xiaomi_AIoT_Router_AX9000 Xiaomi_AIoT_Router_AX9000_1 = new Xiaomi_AIoT_Router_AX9000();
                    Xiaomi_AIoT_Router_AX9000_1.KeyboardInput();
                    Xiaomi_AIoT_Router_AX9000_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[15] = Xiaomi_AIoT_Router_AX9000_1.Xiaomi_AIoT_Router_AX9000_vulnerabilities.length;
                    continue;
               case ("Xiaomi_AX1800_Wireless_Router"): Xiaomi_AX1800_Wireless_Router Xiaomi_AX1800_Wireless_Router_1 = new Xiaomi_AX1800_Wireless_Router();
                    Xiaomi_AX1800_Wireless_Router_1.KeyboardInput();
                    Xiaomi_AX1800_Wireless_Router_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[16] = Xiaomi_AX1800_Wireless_Router_1.Xiaomi_AX1800_Wireless_Router_vulnerabilities.length;
                    continue;
               case ("Xiaomi_Mi_Portable_WiFi_8GB_White"): Xiaomi_Mi_Portable_WiFi_8GB_White Xiaomi_Mi_Portable_WiFi_8GB_White_1 = new Xiaomi_Mi_Portable_WiFi_8GB_White();
                    Xiaomi_Mi_Portable_WiFi_8GB_White_1.KeyboardInput();
                    Xiaomi_Mi_Portable_WiFi_8GB_White_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[17] = Xiaomi_Mi_Portable_WiFi_8GB_White_1.Xiaomi_Mi_Portable_WiFi_8GB_White_vulnerabilities.length;
                    continue;
               case ("Xiaomi_Mi_Powerline_WiFi_Adapter"): Xiaomi_Mi_Powerline_WiFi_Adapter Xiaomi_Mi_Powerline_WiFi_Adapter_1 = new Xiaomi_Mi_Powerline_WiFi_Adapter();
                    Xiaomi_Mi_Powerline_WiFi_Adapter_1.KeyboardInput();
                    Xiaomi_Mi_Powerline_WiFi_Adapter_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[18] = Xiaomi_Mi_Powerline_WiFi_Adapter_1.Xiaomi_Mi_Powerline_WiFi_Adapter_vulnerabilities.length;
                    continue;
               case ("Xiaomi_Mi_WiFi_Mesh_Router"): Xiaomi_Mi_WiFi_Mesh_Router Xiaomi_Mi_WiFi_Mesh_Router_1 = new Xiaomi_Mi_WiFi_Mesh_Router();
                    Xiaomi_Mi_WiFi_Mesh_Router_1.KeyboardInput();
                    Xiaomi_Mi_WiFi_Mesh_Router_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[19] = Xiaomi_Mi_WiFi_Mesh_Router_1.Xiaomi_Mi_WiFi_Mesh_Router_vulnerabilities.length;
                    continue;
               case ("Xiaomi_Mi_WiFi_Router_2_1TB"): Xiaomi_Mi_WiFi_Router_2_1TB Xiaomi_Mi_WiFi_Router_2_1TB_1 = new Xiaomi_Mi_WiFi_Router_2_1TB();
                    Xiaomi_Mi_WiFi_Router_2_1TB_1.KeyboardInput();
                    Xiaomi_Mi_WiFi_Router_2_1TB_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[20] = Xiaomi_Mi_WiFi_Router_2_1TB_1.Xiaomi_Mi_WiFi_Router_2_1TB_vulnerabilities.length;
                    continue;
               case ("Xiaomi_Mi_WiFi_Router_3A"): Xiaomi_Mi_WiFi_Router_3A Xiaomi_Mi_WiFi_Router_3A_1 = new Xiaomi_Mi_WiFi_Router_3A();
                    Xiaomi_Mi_WiFi_Router_3A_1.KeyboardInput();
                    Xiaomi_Mi_WiFi_Router_3A_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[21] = Xiaomi_Mi_WiFi_Router_3A_1.Xiaomi_Mi_WiFi_Router_3A_vulnerabilities.length;
                    continue;
               case ("Xiaomi_Mi_WiFi_Router_HD_2TB"): Xiaomi_Mi_WiFi_Router_HD_2TB Xiaomi_Mi_WiFi_Router_HD_2TB_1 = new Xiaomi_Mi_WiFi_Router_HD_2TB();
                    Xiaomi_Mi_WiFi_Router_HD_2TB_1.KeyboardInput();
                    Xiaomi_Mi_WiFi_Router_HD_2TB_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[22] = Xiaomi_Mi_WiFi_Router_HD_2TB_1.Xiaomi_Mi_WiFi_Router_HD_2TB_vulnerabilities.length;
                    continue;
               case ("Xiaomi_Mi_WiFi_Router_Nano"): Xiaomi_Mi_WiFi_Router_Nano Xiaomi_Mi_WiFi_Router_Nano_1 = new Xiaomi_Mi_WiFi_Router_Nano();
                    Xiaomi_Mi_WiFi_Router_Nano_1.KeyboardInput();
                    Xiaomi_Mi_WiFi_Router_Nano_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[23] = Xiaomi_Mi_WiFi_Router_Nano_1.Xiaomi_Mi_WiFi_Router_Nano_vulnerabilities.length;
                    continue;
               case ("Xiaomi_Mi_WiFi_Router_Pro"): Xiaomi_Mi_WiFi_Router_Pro Xiaomi_Mi_WiFi_Router_Pro_1 = new Xiaomi_Mi_WiFi_Router_Pro();
                    Xiaomi_Mi_WiFi_Router_Pro_1.KeyboardInput();
                    Xiaomi_Mi_WiFi_Router_Pro_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[24] = Xiaomi_Mi_WiFi_Router_Pro_1.Xiaomi_Mi_WiFi_Router_Pro_vulnerabilities.length;
                    continue;
               case ("Xiaomi_Net_WiFi_Router_4"): Xiaomi_Net_WiFi_Router_4 Xiaomi_Net_WiFi_Router_4_1 = new Xiaomi_Net_WiFi_Router_4();
                    Xiaomi_Net_WiFi_Router_4_1.KeyboardInput();
                    Xiaomi_Net_WiFi_Router_4_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[25] = Xiaomi_Net_WiFi_Router_4_1.Google_Home_Voice_Controller_vulnerabilities.length;
                    continue;
               case ("Aqara_Human_Body_Sensor"): Aqara_Human_Body_Sensor Aqara_Human_Body_Sensor_1 = new Aqara_Human_Body_Sensor();
                    Aqara_Human_Body_Sensor_1.KeyboardInput();
                    Aqara_Human_Body_Sensor_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Sensor&search_type=all");
                    continue;
               case ("Aqara_Smart_Socket_ZigBee_Version"): Aqara_Smart_Socket_ZigBee_Version Aqara_Smart_Socket_ZigBee_Version_1 = new Aqara_Smart_Socket_ZigBee_Version();
                    Aqara_Smart_Socket_ZigBee_Version_1.KeyboardInput();
                    Aqara_Smart_Socket_ZigBee_Version_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Smart+socket&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[26] = Aqara_Smart_Socket_ZigBee_Version_1.Aqara_Smart_Socket_ZigBee_Version_vulnerabilities.length;
                    continue;
               case ("Aqara_Smart_Wireless_Switch"): Aqara_Smart_Wireless_Switch Aqara_Smart_Wireless_Switch_1 = new Aqara_Smart_Wireless_Switch();
                    Aqara_Smart_Wireless_Switch_1.KeyboardInput();
                    Aqara_Smart_Wireless_Switch_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Smart+socket&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[27] = Aqara_Smart_Wireless_Switch_1.Aqara_Smart_Wireless_Switch_vulnerabilities.length;
                    continue;
               case ("Aqara_Temperature_Humidity_Sensor"): Aqara_Temperature_Humidity_Sensor Aqara_Temperature_Humidity_Sensor_1 = new Aqara_Temperature_Humidity_Sensor();
                    Aqara_Temperature_Humidity_Sensor_1.KeyboardInput();
                    Aqara_Temperature_Humidity_Sensor_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Sensor&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[28] = Aqara_Temperature_Humidity_Sensor_1.Aqara_Temperature_Humidity_Sensor_vulnerabilities.length;
                    continue;
               case ("Mi_Home_Honeywell_Gas_Leak_Detector"): Mi_Home_Honeywell_Gas_Leak_Detector Mi_Home_Honeywell_Gas_Leak_Detector_1 = new Mi_Home_Honeywell_Gas_Leak_Detector();
                    Mi_Home_Honeywell_Gas_Leak_Detector_1.KeyboardInput();
                    Mi_Home_Honeywell_Gas_Leak_Detector_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Sensor&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[29] = Mi_Home_Honeywell_Gas_Leak_Detector_1.Mi_Home_Honeywell_Gas_Leak_Detector_vulnerabilities.length;
                    continue;
               case ("Mi_Home_Mijia_ClearGrass_Air_Detector_CGS1"): Mi_Home_Mijia_ClearGrass_Air_Detector_CGS1 Mi_Home_Mijia_ClearGrass_Air_Detector_CGS1_1 = new Mi_Home_Mijia_ClearGrass_Air_Detector_CGS1();
                    Mi_Home_Mijia_ClearGrass_Air_Detector_CGS1_1.KeyboardInput();
                    Mi_Home_Mijia_ClearGrass_Air_Detector_CGS1_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Sensor&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[30] = Mi_Home_Mijia_ClearGrass_Air_Detector_CGS1_1.Mi_Home_Mijia_ClearGrass_Air_Detector_CGS1_vulnerabilities.length;
                    continue;
               case ("Mi_Home_Mijia_Honeywell_Smoke_Detector"): Mi_Home_Mijia_Honeywell_Smoke_Detector Mi_Home_Mijia_Honeywell_Smoke_Detector_1 = new Mi_Home_Mijia_Honeywell_Smoke_Detector();
                    Mi_Home_Mijia_Honeywell_Smoke_Detector_1.KeyboardInput();
                    Mi_Home_Mijia_Honeywell_Smoke_Detector_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Sensor&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[31] = Mi_Home_Mijia_Honeywell_Smoke_Detector_1.Mi_Home_Mijia_Honeywell_Smoke_Detector_vulnerabilities.length;
                    continue;
               case ("Qingping_Bluetooth_Gateway"): Qingping_Bluetooth_Gateway Qingping_Bluetooth_Gateway_1 = new Qingping_Bluetooth_Gateway();
                    Qingping_Bluetooth_Gateway_1.KeyboardInput();
                    Qingping_Bluetooth_Gateway_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=bluetooth+gateway&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[32] = Qingping_Bluetooth_Gateway_1.Qingping_Bluetooth_Gateway_vulnerabilities.length;
                    continue;
               case ("Xiaofei_PTH_3M_Air_Detector"): Xiaofei_PTH_3M_Air_Detector Xiaofei_PTH_3M_Air_Detector_1 = new Xiaofei_PTH_3M_Air_Detector();
                    Xiaofei_PTH_3M_Air_Detector_1.KeyboardInput();
                    Xiaofei_PTH_3M_Air_Detector_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Air+Detector&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[33] = Xiaofei_PTH_3M_Air_Detector_1.Xiaofei_PTH_3M_Air_Detector_vulnerabilities.length;
                    continue;
               case ("Xiaomi_Honeywell_Formaldehyde_Monitor"): Xiaomi_Honeywell_Formaldehyde_Monitor Xiaomi_Honeywell_Formaldehyde_Monitor_1 = new Xiaomi_Honeywell_Formaldehyde_Monitor();
                    Xiaomi_Honeywell_Formaldehyde_Monitor_1.KeyboardInput();
                    Xiaomi_Honeywell_Formaldehyde_Monitor_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Air+Detector&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[34] = Xiaomi_Honeywell_Formaldehyde_Monitor_1.Xiaomi_Honeywell_Formaldehyde_Monitor_vulnerabilities.length;
                    continue;
               case ("Google_Nest_Hub_2nd_gen"): Google_Nest_Hub_2nd_gen Google_Nest_Hub_2nd_gen_1 = new Google_Nest_Hub_2nd_gen();
                    Google_Nest_Hub_2nd_gen_1.KeyboardInput();
                    Google_Nest_Hub_2nd_gen_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=Nest+Hub&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[35] = Google_Nest_Hub_2nd_gen_1.Google_Nest_Hub_2nd_gen_vulnerabilities.length;
                    continue;
               case ("Google_Nest_Mini"): Google_Nest_Mini Google_Nest_Mini_1 = new Google_Nest_Mini();
                    Google_Nest_Mini_1.KeyboardInput();
                    Google_Nest_Mini_1.Display("\"https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=Nest+Hub&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[36] = Google_Nest_Mini_1.Google_Nest_Mini_vulnerabilities.length;
                    continue;
               case ("Google_Nest_Wifi"): Google_Nest_Wifi Google_Nest_Wifi_1 = new Google_Nest_Wifi();
                    Google_Nest_Wifi_1.KeyboardInput();
                    Google_Nest_Wifi_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=Nest+Hub&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[37] = Google_Nest_Wifi_1.Google_Nest_Wifi_vulnerabilities.length;
                    continue;
               case ("Google_Home_Voice_Controller"): Google_Home_Voice_Controller Google_Home_Voice_Controller_1 = new Google_Home_Voice_Controller();
                    Google_Home_Voice_Controller_1.KeyboardInput();
                    Google_Home_Voice_Controller_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=Voice+Controller&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[38] = Google_Home_Voice_Controller_1.Google_Home_Voice_Controller_vulnerabilities.length;
                    continue;
               case ("Nest_Hello_Doorbell"): Nest_Hello_Doorbell Nest_Hello_Doorbell_1 = new Nest_Hello_Doorbell();
                    Nest_Hello_Doorbell_1.KeyboardInput();
                    Nest_Hello_Doorbell_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=DoorBell&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[39] = Nest_Hello_Doorbell_1.Nest_Hello_Doorbell_vulnerabilities.length;
                    continue;
               case ("NetStick_Ethernet_Cradle"): NetStick_Ethernet_Cradle NetStick_Ethernet_Cradle_1 = new NetStick_Ethernet_Cradle();
                    NetStick_Ethernet_Cradle_1.KeyboardInput();
                    NetStick_Ethernet_Cradle_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=NetStick+&search_type=all");
                    RiskCalculation_Prod.number_of_probabilities[40] = NetStick_Ethernet_Cradle_1.NetStick_Ethernet_Cradle_vulnerabilities.length;
                    continue;

            }
           System.out.println("----------------------------------------------------------");

        }
    }
}


/*веротности берём однотипные для каждого типа */