package MainClass;
import math.RiskCalculation;
import amazon_systems.*;
import cisco_devices.*;
import google_hubs_etc.*;
import google_sensors.*;
import netstick_devices.*;
import xiaomi_routers.*;
import xiaomi_sockets_sensors.*;
import java.io.*;



public class BodyCode {



    public static int number;
    public static void main(String[] args) throws IOException {
               InputStream inputStream = System.in;

        Reader inputStreamReader = new InputStreamReader(inputStream);
        BufferedReader reader = new BufferedReader(inputStreamReader);
        BufferedReader reader_iot = new BufferedReader(inputStreamReader);



        System.out.println("Введите количество устройств:");
        number = Integer.parseInt(reader.readLine());
        RiskCalculation RiskCalculation_Prod = new RiskCalculation();
        for (int i = 0; i < number; i++) {
            System.out.println("Введите однозначный идентификатор устройства в формате Вендор_тип устройства");
            String identifier = reader.readLine();
            switch (identifier) {
               case ("Amazon_Echo_Flex"): Amazon_Echo_Flex Amazon_Echo_Flex_1 = new Amazon_Echo_Flex();
                    Amazon_Echo_Flex_1.KeyboardInput();
                    Amazon_Echo_Flex_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Amazon+Flex&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Amazon_Echo_Flex_1.damage);
                    continue;
               case ("Amazon_Echo_fourth_gen"): Amazon_Echo_fourth_gen Amazon_Echo_fourth_gen_1 = new Amazon_Echo_fourth_gen();
                    Amazon_Echo_fourth_gen_1.KeyboardInput();
                    Amazon_Echo_fourth_gen_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Aamazon&cpe_product=cpe%3A%2F%3Aamazon%3Aecho_plus_firmware");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Amazon_Echo_fourth_gen_1.damage);
                    continue;
               case ("Amazon_Echo_Show_8"): Amazon_Echo_Show_8 Amazon_Echo_Show_8_1 = new Amazon_Echo_Show_8();
                    Amazon_Echo_Show_8_1.KeyboardInput();
                    Amazon_Echo_Show_8_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Aamazon&cpe_product=cpe%3A%2F%3Aamazon%3Aecho_plus_firmware");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Amazon_Echo_Show_8_1.damage);
                    continue;
               case ("August_WiFi_Smart_Lock"): August_WiFi_Smart_Lock August_WiFi_Smart_Lock_1 = new August_WiFi_Smart_Lock();
                    August_WiFi_Smart_Lock_1.KeyboardInput();
                    August_WiFi_Smart_Lock_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Aamazon&cpe_product=cpe%3A%2F%3Aamazon%3Aecho_plus_firmware");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*August_WiFi_Smart_Lock_1.damage);
                    continue;
               case ("Ecobee_Smart_Thermostat"): Ecobee_Smart_Thermostat Ecobee_Smart_Thermostat_1 = new Ecobee_Smart_Thermostat();
                    Ecobee_Smart_Thermostat_1.KeyboardInput();
                    Ecobee_Smart_Thermostat_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=thermostat&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Ecobee_Smart_Thermostat_1.damage);
                    continue;
               case ("Ring_Peephole_Cam"): Ring_Peephole_Cam Ring_Peephole_Cam_1 = new Ring_Peephole_Cam();
                    Ring_Peephole_Cam_1.KeyboardInput();
                    Ring_Peephole_Cam_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=telephone+camera&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Ring_Peephole_Cam_1.damage);
                    continue;
               case ("Cisco_1100_Series_Industrial_Integrated_Services_Router"): Cisco_1100_Series_Industrial_Integrated_Services_Router Cisco_1100_Series_Industrial_Integrated_Services_Router_1 = new Cisco_1100_Series_Industrial_Integrated_Services_Router();
                    Cisco_1100_Series_Industrial_Integrated_Services_Router_1.KeyboardInput();
                    Cisco_1100_Series_Industrial_Integrated_Services_Router_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Acisco&cpe_product=cpe%3A%2F%3Acisco%3A1100");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Cisco_1100_Series_Industrial_Integrated_Services_Router_1.damage);
                    continue;
               case ("Cisco_Catalyst_IE3x00_Rugged_Switches"): Cisco_Catalyst_IE3x00_Rugged_Switches Cisco_Catalyst_IE3x00_Rugged_Switches_1 = new Cisco_Catalyst_IE3x00_Rugged_Switches();
                    Cisco_Catalyst_IE3x00_Rugged_Switches_1.KeyboardInput();
                    Cisco_Catalyst_IE3x00_Rugged_Switches_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_product=cpe%3A%2F%3A%3A300_series_managed_switch_firmware");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Cisco_Catalyst_IE3x00_Rugged_Switches_1.damage);
                    continue;
               case ("Cisco_Catalyst_IE3400_Heavy_Duty_Series"): Cisco_Catalyst_IE3400_Heavy_Duty_Series Cisco_Catalyst_IE3400_Heavy_Duty_Series_1 = new Cisco_Catalyst_IE3400_Heavy_Duty_Series();
                    Cisco_Catalyst_IE3400_Heavy_Duty_Series_1.KeyboardInput();
                    Cisco_Catalyst_IE3400_Heavy_Duty_Series_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Alenovo&cpe_product=cpe%3A%2F%3A%3A340c-15ast");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Cisco_Catalyst_IE3400_Heavy_Duty_Series_1.damage);
                    continue;
               case ("Cisco_Catalyst_IR1800_Rugged_Series_Router"): Cisco_Catalyst_IR1800_Rugged_Series_Router Cisco_Catalyst_IR1800_Rugged_Series_Router_1 = new Cisco_Catalyst_IR1800_Rugged_Series_Router();
                    Cisco_Catalyst_IR1800_Rugged_Series_Router_1.KeyboardInput();
                    Cisco_Catalyst_IR1800_Rugged_Series_Router_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Acisco&cpe_product=cpe%3A%2F%3A%3A1801_integrated_service_router");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Cisco_Catalyst_IR1800_Rugged_Series_Router_1.damage);
                    continue;
               case ("Cisco_Catalyst_IR8100_Heavy_Duty_Series_Router"): Cisco_Catalyst_IR8100_Heavy_Duty_Series_Router Cisco_Catalyst_IR8100_Heavy_Duty_Series_Router_1 = new Cisco_Catalyst_IR8100_Heavy_Duty_Series_Router();
                    Cisco_Catalyst_IR8100_Heavy_Duty_Series_Router_1.KeyboardInput();
                    Cisco_Catalyst_IR8100_Heavy_Duty_Series_Router_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Acisco&cpe_product=cpe%3A%2F%3A%3A1801_integrated_service_router");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Cisco_Catalyst_IR8100_Heavy_Duty_Series_Router_1.damage);
                    continue;
               case ("Redmi_AC2100_Router"): Redmi_AC2100_Router Redmi_AC2100_Router_1 = new Redmi_AC2100_Router();
                    Redmi_AC2100_Router_1.KeyboardInput();
                    Redmi_AC2100_Router_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                   RiskCalculation_Prod.calculateFactorial();
                   RiskCalculation_Prod.calcfact();
                   RiskCalculation_Prod.helper();
                   System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Redmi_AC2100_Router_1.damage);
                    continue;
               case ("Redmi_AX6_Router"): Redmi_AX6_Router Redmi_AX6_Router_1 = new Redmi_AX6_Router();
                    Redmi_AX6_Router_1.KeyboardInput();
                    Redmi_AX6_Router_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Redmi_AX6_Router_1.damage);
                    continue;
               case ("Xiaomi_AC2100_Wireless_Wifi_Router"): Xiaomi_AC2100_Wireless_Wifi_Router Xiaomi_AC2100_Wireless_Wifi_Router_1 = new Xiaomi_AC2100_Wireless_Wifi_Router();
                    Xiaomi_AC2100_Wireless_Wifi_Router_1.KeyboardInput();
                    Xiaomi_AC2100_Wireless_Wifi_Router_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Xiaomi_AC2100_Wireless_Wifi_Router_1.damage);
                    continue;
               case ("Xiaomi_AIoT_Router_AC2350"): Xiaomi_AIoT_Router_AC2350 Xiaomi_AIoT_Router_AC2350_1 = new Xiaomi_AIoT_Router_AC2350();
                    Xiaomi_AIoT_Router_AC2350_1.KeyboardInput();
                    Xiaomi_AIoT_Router_AC2350_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()* Xiaomi_AIoT_Router_AC2350_1.damage);
                    continue;
               case ("Xiaomi_AIoT_Router_AX9000"): Xiaomi_AIoT_Router_AX9000 Xiaomi_AIoT_Router_AX9000_1 = new Xiaomi_AIoT_Router_AX9000();
                    Xiaomi_AIoT_Router_AX9000_1.KeyboardInput();
                    Xiaomi_AIoT_Router_AX9000_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Xiaomi_AIoT_Router_AX9000_1.damage);
                    continue;
               case ("Xiaomi_AX1800_Wireless_Router"): Xiaomi_AX1800_Wireless_Router Xiaomi_AX1800_Wireless_Router_1 = new Xiaomi_AX1800_Wireless_Router();
                    Xiaomi_AX1800_Wireless_Router_1.KeyboardInput();
                    Xiaomi_AX1800_Wireless_Router_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Xiaomi_AX1800_Wireless_Router_1.damage);
                    continue;
               case ("Xiaomi_Mi_Portable_WiFi_8GB_White"): Xiaomi_Mi_Portable_WiFi_8GB_White Xiaomi_Mi_Portable_WiFi_8GB_White_1 = new Xiaomi_Mi_Portable_WiFi_8GB_White();
                    Xiaomi_Mi_Portable_WiFi_8GB_White_1.KeyboardInput();
                    Xiaomi_Mi_Portable_WiFi_8GB_White_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Xiaomi_Mi_Portable_WiFi_8GB_White_1.damage);
                    continue;
               case ("Xiaomi_Mi_Powerline_WiFi_Adapter"): Xiaomi_Mi_Powerline_WiFi_Adapter Xiaomi_Mi_Powerline_WiFi_Adapter_1 = new Xiaomi_Mi_Powerline_WiFi_Adapter();
                    Xiaomi_Mi_Powerline_WiFi_Adapter_1.KeyboardInput();
                    Xiaomi_Mi_Powerline_WiFi_Adapter_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Xiaomi_Mi_Powerline_WiFi_Adapter_1.damage);
                    continue;
               case ("Xiaomi_Mi_WiFi_Mesh_Router"): Xiaomi_Mi_WiFi_Mesh_Router Xiaomi_Mi_WiFi_Mesh_Router_1 = new Xiaomi_Mi_WiFi_Mesh_Router();
                    Xiaomi_Mi_WiFi_Mesh_Router_1.KeyboardInput();
                    Xiaomi_Mi_WiFi_Mesh_Router_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Xiaomi_Mi_WiFi_Mesh_Router_1.damage);
                    continue;
               case ("Xiaomi_Mi_WiFi_Router_2_1TB"): Xiaomi_Mi_WiFi_Router_2_1TB Xiaomi_Mi_WiFi_Router_2_1TB_1 = new Xiaomi_Mi_WiFi_Router_2_1TB();
                    Xiaomi_Mi_WiFi_Router_2_1TB_1.KeyboardInput();
                    Xiaomi_Mi_WiFi_Router_2_1TB_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Xiaomi_Mi_WiFi_Router_2_1TB_1.damage);
                    continue;
               case ("Xiaomi_Mi_WiFi_Router_3A"): Xiaomi_Mi_WiFi_Router_3A Xiaomi_Mi_WiFi_Router_3A_1 = new Xiaomi_Mi_WiFi_Router_3A();
                    Xiaomi_Mi_WiFi_Router_3A_1.KeyboardInput();
                    Xiaomi_Mi_WiFi_Router_3A_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Xiaomi_Mi_WiFi_Router_3A_1.damage);
                    continue;
               case ("Xiaomi_Mi_WiFi_Router_HD_2TB"): Xiaomi_Mi_WiFi_Router_HD_2TB Xiaomi_Mi_WiFi_Router_HD_2TB_1 = new Xiaomi_Mi_WiFi_Router_HD_2TB();
                    Xiaomi_Mi_WiFi_Router_HD_2TB_1.KeyboardInput();
                    Xiaomi_Mi_WiFi_Router_HD_2TB_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Xiaomi_Mi_WiFi_Router_HD_2TB_1.damage);
                    continue;
               case ("Xiaomi_Mi_WiFi_Router_Nano"): Xiaomi_Mi_WiFi_Router_Nano Xiaomi_Mi_WiFi_Router_Nano_1 = new Xiaomi_Mi_WiFi_Router_Nano();
                    Xiaomi_Mi_WiFi_Router_Nano_1.KeyboardInput();
                    Xiaomi_Mi_WiFi_Router_Nano_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Xiaomi_Mi_WiFi_Router_Nano_1.damage);
                    continue;
               case ("Xiaomi_Mi_WiFi_Router_Pro"): Xiaomi_Mi_WiFi_Router_Pro Xiaomi_Mi_WiFi_Router_Pro_1 = new Xiaomi_Mi_WiFi_Router_Pro();
                    Xiaomi_Mi_WiFi_Router_Pro_1.KeyboardInput();
                    Xiaomi_Mi_WiFi_Router_Pro_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Xiaomi_Mi_WiFi_Router_Pro_1.damage);
                    continue;
               case ("Xiaomi_Net_WiFi_Router_4"): Xiaomi_Net_WiFi_Router_4 Xiaomi_Net_WiFi_Router_4_1 = new Xiaomi_Net_WiFi_Router_4();
                    Xiaomi_Net_WiFi_Router_4_1.KeyboardInput();
                    Xiaomi_Net_WiFi_Router_4_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Xiaomi+Router&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Xiaomi_Net_WiFi_Router_4_1.damage);
                    continue;
               case ("Aqara_Human_Body_Sensor"): Aqara_Human_Body_Sensor Aqara_Human_Body_Sensor_1 = new Aqara_Human_Body_Sensor();
                    Aqara_Human_Body_Sensor_1.KeyboardInput();
                    Aqara_Human_Body_Sensor_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Sensor&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Aqara_Human_Body_Sensor_1.damage);
                    continue;
               case ("Aqara_Smart_Socket_ZigBee_Version"): Aqara_Smart_Socket_ZigBee_Version Aqara_Smart_Socket_ZigBee_Version_1 = new Aqara_Smart_Socket_ZigBee_Version();
                    Aqara_Smart_Socket_ZigBee_Version_1.KeyboardInput();
                    Aqara_Smart_Socket_ZigBee_Version_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Smart+socket&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Aqara_Smart_Socket_ZigBee_Version_1.damage);
                    continue;
               case ("Aqara_Smart_Wireless_Switch"): Aqara_Smart_Wireless_Switch Aqara_Smart_Wireless_Switch_1 = new Aqara_Smart_Wireless_Switch();
                    Aqara_Smart_Wireless_Switch_1.KeyboardInput();
                    Aqara_Smart_Wireless_Switch_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Smart+socket&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Aqara_Smart_Wireless_Switch_1.damage);
                    continue;
               case ("Aqara_Temperature_Humidity_Sensor"): Aqara_Temperature_Humidity_Sensor Aqara_Temperature_Humidity_Sensor_1 = new Aqara_Temperature_Humidity_Sensor();
                    Aqara_Temperature_Humidity_Sensor_1.KeyboardInput();
                    Aqara_Temperature_Humidity_Sensor_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Sensor&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()* Aqara_Temperature_Humidity_Sensor_1.damage);
                    continue;
               case ("Mi_Home_Honeywell_Gas_Leak_Detector"): Mi_Home_Honeywell_Gas_Leak_Detector Mi_Home_Honeywell_Gas_Leak_Detector_1 = new Mi_Home_Honeywell_Gas_Leak_Detector();
                    Mi_Home_Honeywell_Gas_Leak_Detector_1.KeyboardInput();
                    Mi_Home_Honeywell_Gas_Leak_Detector_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Sensor&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Mi_Home_Honeywell_Gas_Leak_Detector_1.damage);
                    continue;
               case ("Mi_Home_Mijia_ClearGrass_Air_Detector_CGS1"): Mi_Home_Mijia_ClearGrass_Air_Detector_CGS1 Mi_Home_Mijia_ClearGrass_Air_Detector_CGS1_1 = new Mi_Home_Mijia_ClearGrass_Air_Detector_CGS1();
                    Mi_Home_Mijia_ClearGrass_Air_Detector_CGS1_1.KeyboardInput();
                    Mi_Home_Mijia_ClearGrass_Air_Detector_CGS1_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Sensor&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()* Mi_Home_Mijia_ClearGrass_Air_Detector_CGS1_1.damage);
                    continue;
               case ("Mi_Home_Mijia_Honeywell_Smoke_Detector"): Mi_Home_Mijia_Honeywell_Smoke_Detector Mi_Home_Mijia_Honeywell_Smoke_Detector_1 = new Mi_Home_Mijia_Honeywell_Smoke_Detector();
                    Mi_Home_Mijia_Honeywell_Smoke_Detector_1.KeyboardInput();
                    Mi_Home_Mijia_Honeywell_Smoke_Detector_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Sensor&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Mi_Home_Mijia_Honeywell_Smoke_Detector_1.damage);
                    continue;
               case ("Qingping_Bluetooth_Gateway"): Qingping_Bluetooth_Gateway Qingping_Bluetooth_Gateway_1 = new Qingping_Bluetooth_Gateway();
                    Qingping_Bluetooth_Gateway_1.KeyboardInput();
                    Qingping_Bluetooth_Gateway_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=bluetooth+gateway&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Qingping_Bluetooth_Gateway_1.damage);
                    continue;
               case ("Xiaofei_PTH_3M_Air_Detector"): Xiaofei_PTH_3M_Air_Detector Xiaofei_PTH_3M_Air_Detector_1 = new Xiaofei_PTH_3M_Air_Detector();
                    Xiaofei_PTH_3M_Air_Detector_1.KeyboardInput();
                    Xiaofei_PTH_3M_Air_Detector_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Air+Detector&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Xiaofei_PTH_3M_Air_Detector_1.damage);
                    continue;
               case ("Xiaomi_Honeywell_Formaldehyde_Monitor"): Xiaomi_Honeywell_Formaldehyde_Monitor Xiaomi_Honeywell_Formaldehyde_Monitor_1 = new Xiaomi_Honeywell_Formaldehyde_Monitor();
                    Xiaomi_Honeywell_Formaldehyde_Monitor_1.KeyboardInput();
                    Xiaomi_Honeywell_Formaldehyde_Monitor_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=Air+Detector&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Xiaomi_Honeywell_Formaldehyde_Monitor_1.damage);
                    continue;
               case ("Google_Nest_Hub_2nd_gen"): Google_Nest_Hub_2nd_gen Google_Nest_Hub_2nd_gen_1 = new Google_Nest_Hub_2nd_gen();
                    Google_Nest_Hub_2nd_gen_1.KeyboardInput();
                    Google_Nest_Hub_2nd_gen_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=Nest+Hub&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Google_Nest_Hub_2nd_gen_1.damage);
                    continue;
               case ("Google_Nest_Mini"): Google_Nest_Mini Google_Nest_Mini_1 = new Google_Nest_Mini();
                    Google_Nest_Mini_1.KeyboardInput();
                    Google_Nest_Mini_1.Display("\"https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=Nest+Hub&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Google_Nest_Mini_1.damage);
                    continue;
               case ("Google_Nest_Wifi"): Google_Nest_Wifi Google_Nest_Wifi_1 = new Google_Nest_Wifi();
                    Google_Nest_Wifi_1.KeyboardInput();
                    Google_Nest_Wifi_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=Nest+Hub&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Google_Nest_Wifi_1.damage);
                    continue;
               case ("Google_Home_Voice_Controller"): Google_Home_Voice_Controller Google_Home_Voice_Controller_1 = new Google_Home_Voice_Controller();
                    Google_Home_Voice_Controller_1.KeyboardInput();
                    Google_Home_Voice_Controller_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=Voice+Controller&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Google_Home_Voice_Controller_1.damage);
                    continue;
               case ("Nest_Hello_Doorbell"): Nest_Hello_Doorbell Nest_Hello_Doorbell_1 = new Nest_Hello_Doorbell();
                    Nest_Hello_Doorbell_1.KeyboardInput();
                    Nest_Hello_Doorbell_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=DoorBell&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*Nest_Hello_Doorbell_1.damage);
                    continue;
               case ("NetStick_Ethernet_Cradle"): NetStick_Ethernet_Cradle NetStick_Ethernet_Cradle_1 = new NetStick_Ethernet_Cradle();
                    NetStick_Ethernet_Cradle_1.KeyboardInput();
                    NetStick_Ethernet_Cradle_1.Display("https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&query=NetStick+&search_type=all");
                    RiskCalculation_Prod.calculateFactorial();
                    RiskCalculation_Prod.calcfact();
                    RiskCalculation_Prod.helper();
                    System.out.println("Риск данного устройства при заданных параметрах:" + RiskCalculation_Prod.get_risk_helper()*NetStick_Ethernet_Cradle_1.damage);
                    continue;

            }
           System.out.println("----------------------------------------------------------");

        }
    }
}


/*веротности берём однотипные для каждого типа */